Repository jenkins-x/environment-tekton-weasel-dev, pull requests merged in 2019-08, with the labels that each got.

#2 feat: added jx-scheduler
  env/prow/values.tmpl.yaml
  env/templates/jx-scheduler.yaml
  jenkins-x.yml
Labels: approved, size/L

#4 fix: using updated pipeline image
  env/prow/values.tmpl.yaml
  jenkins-x.yml
Labels: size/S

#5 fix: using an old pipeline image
  env/prow/values.tmpl.yaml
  env/templates/env-scheduler.yaml
Labels: size/S

#7 fix: update builder to wip102
  jenkins-x.yml
Labels: size/XS

#8 fix: setting vault name in requirements
  jx-requirements.yml
Labels: size/XS

#9 fix: removing verify env from the pipeline
  jenkins-x.yml
Labels: size/XS

#6 fix: fix pipeline reconcilation
  env/prow/values.tmpl.yaml
Labels: size/XS

#10 chore: only actually update pipeline
  env/prow/values.tmpl.yaml
  jenkins-x.yml
Labels: approved, lgtm, size/S

#11 feat: attempting to import repository
  env/templates/jx-scheduler.yaml
  repositories/templates/jx-group.yaml
  repositories/templates/repositories.yaml
Labels: approved, size/M

#12 fix: revert context
  env/templates/jx-scheduler.yaml
Labels: approved, size/M

#13 fix: yaml structure
  repositories/templates/jx-group.yaml
Labels: approved, size/XS

#14 fix: add org to spec
  repositories/templates/repositories.yaml
Labels: approved, size/XS

#17 fix: only put overrides in `jx-scheduler`
  env/templates/jx-scheduler.yaml
Labels: approved, size/M

#18 fix: correct the name for the source repo
  repositories/templates/repositories.yaml
Labels: approved, size/XS

#19 feat: try to add add context
  env/templates/jx-scheduler.yaml
Labels: approved, size/M

#20 feat: added precommit config
  .pre-commit-config.yaml
  .secrets.baseline
Labels: approved, size/L

#21 fix: rename sourcerepository reference
  repositories/templates/jx-group.yaml
Labels: approved, size/XS

#22 chore: plugin name is label
  env/templates/jx-scheduler.yaml
Labels: approved, size/XS

#23 feat: add Jenkins X BDD service account secret
  env/sa/templates/bdd-secret.yaml
  env/sa/values.yaml
Labels: approved, size/S

#24 feat: add lint and tekton contexts
  env/templates/jx-scheduler.yaml
Labels: approved, size/M

#25 fix: move sa secret to top level environment env templates
  env/templates/bdd-secret.yaml
Labels: approved, size/XS

#26 fix: fix lint context name
  env/templates/jx-scheduler.yaml
Labels: approved, size/XS

#27 fix: add missing context back
  env/templates/jx-scheduler.yaml
Labels: approved, size/XS

#28 fix: move sa values to be tmpl.yaml
  env/sa/values.yaml
  env/templates/bdd-secret.yaml
  env/values.tmpl.yaml
Labels: approved, size/S

#29 fix: update base image
  jenkins-x.yml
Labels: approved, size/XS

#30 fix: remove base64
  env/templates/bdd-secret.yaml
Labels: approved, size/XS

#31 chore: add jx-pipeline-git-github-ghe secret
  env/templates/ghe-secret.yaml
  env/values.tmpl.yaml
Labels: approved, size/S

#32 fix: corrected retrigger commands for tekton context
  env/templates/jx-scheduler.yaml
Labels: approved, size/XS

#33 chore: add more missing secrets
  env/templates/jenkins-x-gke-sa.yaml
  env/templates/test-jenkins-user-secret.yaml
  env/values.tmpl.yaml
Labels: approved, size/M

#34 chore: try and fix multi line secrets and single line entries
  env/templates/jenkins-x-gke-sa.yaml
Labels: approved, size/XS

#35 chore: more test secrets
  env/templates/gh-test-secret.yaml
  env/values.tmpl.yaml
Labels: approved, size/S

#39 fix: step verify env for github secret
  env/templates/gh-test-secret.yaml
  env/templates/test-jenkins-user-secret.yaml
  env/values.tmpl.yaml
Labels: approved, size/XS

#40 fix: secrets that are not multiline file that need to be base64 encoded
  env/templates/gh-test-secret.yaml
  env/templates/ghe-secret.yaml
  env/templates/test-jenkins-user-secret.yaml
  env/values.tmpl.yaml
Labels: approved, size/S

#41 feat: enable meta pipeline
  env/prow/values.tmpl.yaml
Labels: approved, size/XS

#42 fix: use dummy URL annotations to avoid test secret being selected by pipelinerunner
  env/templates/gh-test-secret.yaml
Labels: approved, size/XS

#36 feat: import all repositories
  repositories/templates/cloudbees.yaml
  repositories/templates/jenkins-x-apps.yaml
  repositories/templates/jenkins-x-charts.yaml
  repositories/templates/jenkins-x.yaml
  repositories/templates/repositories.yaml
Labels: approved, size/XXL

#43 fix: step verify and dont verify test git creds
  env/templates/gh-test-secret.yaml
Labels: approved, size/XS

#44 fix: annotation must be strings
  env/templates/gh-test-secret.yaml
Labels: approved, size/XS

#45 fix: removed unused repo
  repositories/templates/cloudbees.yaml
Labels: approved, size/S

#46 fix: use rebase merge method for the jx scheduler
  env/templates/jx-scheduler.yaml
Labels: approved, size/XS

#48 fix: tide rebase strategy
  jenkins-x.yml
Labels: approved, size/XS

#50 revert: enable meta pipeline
  env/prow/values.tmpl.yaml
Labels: approved, size/XS

#38 chore: added in scheduler for jenkins-x-versions
  env/templates/jx-versions-scheduler.yaml
  repositories/templates/jx-versions-group.yaml
Labels: approved, size/L

#51 fix: Add GKE GC cronjob
  env/templates/e2e-gc-cj.yaml
Labels: approved, size/M

#52 feat: add jenkinsxio dockerhub creds
  env/values.tmpl.yaml
Labels: approved, size/XS

#53 fix: try fix docker secrets for tekton
  .secrets.baseline
  env/tekton/values.tmpl.yaml
Labels: approved, size/S

#56 chore: add gcs sa for chartmuseum
  env/templates/chartmuseum-gcs-secret.yaml
  env/values.tmpl.yaml
Labels: approved, size/S

#55 chore: added the gcs-copy job in
  env/Makefile
  env/templates/gcs-copy-cj.yaml
  env/values.tmpl.yaml
Labels: approved, size/M

#54 chore: rename 'promotion-build' to 'pr-build'
  env/templates/default-scheduler.yaml
Labels: approved

#57 fix: allow updatebot PRs to be automatically merged
  env/templates/default-scheduler.yaml
Labels: approved, size/XS

#58 fix: enabled override plugin for prow
  env/templates/default-scheduler.yaml
Labels: approved

#59 fix: override contexts on env-scheduler
  env/templates/env-scheduler.yaml
Labels: approved, size/XS

#60 fix: Update gcactivities to not delete all the things
  env/jenkins-x-platform/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#61 fix: reworked updatebot clause
  env/templates/default-scheduler.yaml
Labels: approved, size/S

#63 chore: make ingress controller HA
  systems/jxing/values.yaml
Labels: approved, size/XS

#62 chore: replace dev/wip images with 0.1.658
  jenkins-x.yml
Labels: approved, size/XS

#66 feat: add sso and dashboard apps
  env/jx-app-sso/values.tmpl.yaml
  env/jx-app-ui/values.tmp.yaml
  env/parameters.yaml
  env/requirements.yaml
  env/templates/700-dashboard-ing.yaml
  env/templates/700-dex-ing.yaml
Labels: approved, size/M

#67 fix: installing sso, need to add parameters to the schema
  env/parameters.schema.json
Labels: approved, size/S

#65 fix: updated image for e2e cron
  env/templates/e2e-gc-cj.yaml
Labels: approved, size/XS

#69 chore: Run gc pods and gc activities every half hour
  env/jenkins-x-platform/values.tmpl.yaml
Labels: approved, size/XS

#71 fix: values from requirements not being used, values template filename needs to be exact
  env/jx-app-sso/values.tmpl.yaml
  env/jx-app-ui/values.tmp.yaml
  env/jx-app-ui/values.tmpl.yaml
Labels: approved, size/S

#72 fix: try adding dashboard secrets as values rather than parameters as right now they are being malformed
  env/jx-app-sso/values.tmpl.yaml
  env/jx-app-sso/values.yaml
  env/parameters.schema.json
  env/parameters.yaml
  env/values.tmpl.yaml
Labels: approved, size/M

#73 fix: Revert "fix: try adding dashboard secrets as values rather than parameters as right now they are being malformed"
  env/jx-app-sso/values.tmpl.yaml
  env/jx-app-sso/values.yaml
  env/parameters.schema.json
  env/parameters.yaml
  env/values.tmpl.yaml
Labels: approved, size/M

#74 fix: indent labels properly
  env/templates/jx-scheduler.yaml
Labels: approved, lgtm, size/XS

#75 fix: enable cronjob that updates version streams nightly
  env/templates/version-stream-update-cj.yaml
Labels: approved, size/M

#76 fix: dex does not need basic auth
  env/templates/700-dex-ing.yaml
  env/values.tmpl.yaml
Labels: approved, size/XS

#77 chore: enable sso so we get dex ingress
  env/values.tmpl.yaml
Labels: approved, size/XS

#78 chore: upgrade UI to latest release
  env/requirements.yaml
Labels: approved, size/XS

#79 fix: latest UI release
  env/requirements.yaml
Labels: approved, size/XS

#80 fix: a bit of a hack to fix required contexts
  env/templates/jx-scheduler.yaml
Labels: approved, size/S

#81 fix: hack to fix required contexts
  env/templates/jx-versions-scheduler.yaml
Labels: approved, size/M

#82 fix: chartmuseum config should be in jenkins-x-platform/values.tmpl.yaml
  env/jenkins-x-platform/values.tmpl.yaml
  env/values.tmpl.yaml
Labels: approved, lgtm, size/S

#83 fix: jx-version-stream-update cronjob needs git info and creds
  env/templates/version-stream-update-cj.yaml
Labels: approved, lgtm, size/S

#84 fix: add the builders, remove cert-manager
  env/templates/version-stream-update-cj.yaml
Labels: approved, lgtm, size/XS

#85 feat: add scheduler and repository for jenkins-x-boot-config
  env/templates/boot-config-scheduler.yaml
  repositories/templates/boot-config-group.yaml
  repositories/templates/jenkins-x.yaml
Labels: approved, lgtm, size/M

#86 fix: Needed a newer image for version stream update cronjob
  OWNERS
  env/templates/version-stream-update-cj.yaml
Labels: approved, lgtm, size/XS

#87 fix: Another attempt to fix the version stream update cronjob
  env/templates/version-stream-update-cj.yaml
Labels: approved, lgtm, size/S

#88 fix: Get rid of dangling dash
  env/templates/version-stream-update-cj.yaml
Labels: approved, lgtm, size/XS

#90 fix: Set PIPELINE_KIND to pick up creds for version stream update
  env/templates/version-stream-update-cj.yaml
Labels: approved, lgtm, size/S

#91 feat: add the bdd-vault context to boot-config scheduler
  env/templates/boot-config-scheduler.yaml
Labels: approved, lgtm, size/S

#49 feat: added in periodic jobs to commenter plugin
  env/templates/default-scheduler.yaml
Labels: approved, size/M

#92 fix: Bump the chartmuseum resource requests and limits
  env/jenkins-x-platform/values.tmpl.yaml
Labels: approved, size/XS

#93 fix: attempt to update periodics
  env/templates/default-scheduler.yaml
Labels: approved, lgtm, size/XS

#94 fix: removed periodics section
  env/templates/default-scheduler.yaml
Labels: approved, lgtm, size/M

#95 fix: curl the chartmuesueum index to force update
  env/templates/gcs-copy-cj.yaml
Labels: approved, lgtm, size/S

#96 chore: let’s name this a bit better!
  env/templates/copy-charts-index-cj.yaml
Labels: approved, lgtm, size/XS

#98 fix: Reenable metapipeline, bump prow pipeline image
  env/prow/values.tmpl.yaml
Labels: approved, lgtm, size/S

#99 fix: Re-disable metapipeline due to json logging breaking tests
  env/prow/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#100 fix: Bump version stream cronjob image to 0.1.672
  env/templates/version-stream-update-cj.yaml
Labels: approved, size/XS

#101 chore: pull in fixes for pr generator
  env/templates/version-stream-update-cj.yaml
Labels: approved, lgtm, size/XS

#104 fix: imported new chart repo
  repositories/templates/jenkins-x-charts.yaml
Labels: approved, lgtm, size/S

#106 fix: dashboard lets enable sso for the UI to get the SSO resource
  env/jx-app-ui/values.tmpl.yaml
Labels: approved, size/XS

#107 fix: dashboard deployment, lets try and override the values correctly
  env/jx-app-ui/values.tmpl.yaml
Labels: approved, size/S

#108 fix: dashboard deployment, lets try and move values to top level for UI and see if they are used then
  .secrets.baseline
  env/jx-app-ui/values.tmpl.yaml
  env/values.tmpl.yaml
Labels: approved, size/S

#109 fix: remove quotes from version stream cronjob args, bump image
  env/templates/version-stream-update-cj.yaml
Labels: approved, lgtm, size/XS

#111 feat: add replicator app so we can replicate the wildcard cert into previews for the UI
  env/jx-app-replicator/templates/README.MD
  env/jx-app-replicator/templates/jx-app-replicator-app.yaml
  env/requirements.yaml
Labels: approved, size/S

#110 fix: Pick up latest image for e2e gc cronjob
  env/templates/e2e-gc-cj.yaml
Labels: approved, size/XS

#112 feat: enable new CI only scheduler
  env/templates/ci-scheduler.yaml
  repositories/templates/ci-group.yaml
  repositories/templates/cloudbees-ci.yaml
Labels: approved, lgtm, size/M

#97 feat: add needs-security-review label to all schedulers
  env/templates/boot-config-scheduler.yaml
  env/templates/default-scheduler.yaml
  env/templates/env-scheduler.yaml
  env/templates/jx-scheduler.yaml
  env/templates/jx-versions-scheduler.yaml
Labels: approved, lgtm, size/S

#117 chore: fix url for chartmuseuem index generation
  env/templates/copy-charts-index-cj.yaml
Labels: approved, lgtm, size/XS

#118 fix: revert to a working dashboard
  env/requirements.yaml
Labels: approved, size/XS
