Repository jenkins-x/environment-tekton-weasel-dev, pull requests merged in 2019-10, with the labels that each got.

#181 fix: Stop using PR-5651 image for controllerbuild
  env/jenkins-x-platform/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#182 chore: add arcalosui-frontend
  repositories/templates/cloudbees.yaml
Labels: approved, lgtm, size/S

#183 chore: initial build for jenkins-x/status-badge
  repositories/templates/jenkins-x.yaml
Labels: approved, size/S

#184 chore: added import for jenkins-x-apps/jx-app-statusbadge
  repositories/templates/jenkins-x-apps.yaml
Labels: approved, size/S

#186 feat: install the statusbadge app into our prod cluster
  README.md
  env/jx-app-statusbadge/README.MD
  env/jx-app-statusbadge/templates/app.yaml
  env/jx-app-statusbadge/values.yaml
  env/requirements.yaml
  env/templates/700-statusbadge-ing.yaml
Labels: approved, size/M

#187 chore: update status-badge to 0.0.7
  env/jx-app-statusbadge/templates/app.yaml
  env/jx-app-statusbadge/values.yaml
  env/requirements.yaml
Labels: approved, size/XS

#188 fix: updated configuration for status app
  env/jx-app-statusbadge/values.yaml
Labels: approved, size/XS

#189 fix: Remove configmaps from controllerbuild role
  env/jenkins-x-platform/values.tmpl.yaml
Labels: approved, lgtm, size/M

#190 fix: Bump version update cronjob builder image
  env/templates/version-stream-update-cj.yaml
Labels: approved, lgtm, size/XS

#191 fix: corrected arcalos master build context
  env/templates/arcalos-versions-scheduler.yaml
Labels: approved, size/XS

#192 feat: enabled automerging of updatebot prs for arcalos
  env/templates/arcalos-versions-scheduler.yaml
Labels: approved, size/S

#193 chore: added config for cloudbees/arcalos-boot-config
  repositories/templates/arcalos-versions-group.yaml
  repositories/templates/cloudbees.yaml
Labels: approved, size/S

#200 fix: Bump e2e image
  env/templates/e2e-gc-cj.yaml
Labels: approved, lgtm, size/XS

#201 feat: enable arcalos cleanup job
  env/templates/arcalos-cleanup-cj.yaml
Labels: approved, size/M

#203 fix: update cj spec
  env/templates/arcalos-cleanup-cj.yaml
Labels: approved, lgtm, size/XS

#204 fix: running arcalos cleanup job as tekton-bot
  env/templates/arcalos-cleanup-cj.yaml
Labels: approved, size/XS

#205 fix: corrected secret mount point for arcalos cron
  env/templates/arcalos-cleanup-cj.yaml
Labels: approved, size/XS

#208 fix: corrected arcalos cleanup job
  env/templates/arcalos-cleanup-cj.yaml
Labels: approved, lgtm, size/S

#211 feat: replace githubapp with lighthouse-githubapp
  repositories/templates/cloudbees.yaml
Labels: approved, lgtm, size/XS

#212 chore: add a netrc secret yaml
  env/templates/netrc-secret.yaml
  env/templates/raccoon-env.yaml
  env/values.tmpl.yaml
Labels: approved, lgtm, size/S

#213 fix: move the bdd tests for vault with tls into versions repository
  env/templates/boot-config-scheduler.yaml
  env/templates/jx-versions-scheduler.yaml
Labels: approved, lgtm, size/M

#214 fix: remove the bdd-vault context from boot-config-scheduler
  env/templates/boot-config-scheduler.yaml
Labels: approved, lgtm, size/XS

#215 fix: add the repository-controller repo
  repositories/templates/cloudbees.yaml
Labels: size/S

#216 fix: rename repository to work around jx bug
  repositories/templates/cloudbees.yaml
Labels: size/XS
