Repository jenkins-x/environment-tekton-weasel-dev, pull requests merged in 2019-09, with the labels that each got.

#119 fix: Bump version stream cronjob image
  env/templates/version-stream-update-cj.yaml
Labels: approved, lgtm, size/XS

#120 fix: deplicate postsubmit config
  env/templates/ci-scheduler.yaml
Labels: approved, size/XS

#123 fix: Update gc activities cronjob image
  env/jenkins-x-platform/values.tmpl.yaml
Labels: approved, size/XS

#124 feat: enable review acting as lgtm
  env/templates/jx-scheduler.yaml
Labels: approved, lgtm, size/XS

#125 chore: add the images context
  env/templates/jx-scheduler.yaml
Labels: approved, size/S

#127 fix: Fix images context regexp
  env/templates/jx-scheduler.yaml
Labels: approved, lgtm, size/XS

#128 fix: add test secrets for bitbucket server and gitlab
  env/templates/bbs-test-secret.yaml
  env/templates/gitlab-test-secret.yaml
  env/values.tmpl.yaml
Labels: approved, lgtm, size/M

#129 fix: add 2 new bdd tests to the version stream
  env/templates/jx-versions-scheduler.yaml
Labels: approved, lgtm, size/M

#130 fix: report_template had wrong index in pulls
  env/templates/default-scheduler.yaml
Labels: approved, lgtm, size/XS

#131 fix: Fix reportTemplate in ci-scheduler.yaml as well
  env/templates/ci-scheduler.yaml
Labels: approved, lgtm, size/XS

#132 feat: add post submit build for boot config scheduler
  env/templates/boot-config-scheduler.yaml
Labels: approved, lgtm, size/XS

#133 chore: Exclude Lighthouse until it gets fixed. =)
  env/templates/version-stream-update-cj.yaml
Labels: approved, lgtm, size/XS

#135 fix: remove git labels from test secrets
  env/prow/values.tmpl.yaml
  env/templates/gh-test-secret.yaml
  env/templates/git-test-bbs-secret.yaml
  env/templates/git-test-ghe-secret.yaml
  env/templates/git-test-gitlab-secret.yaml
Labels: approved, lgtm, size/S

#136 fix: Update gcactivities image and prow pipeline image
  env/jenkins-x-platform/values.tmpl.yaml
  env/prow/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#137 fix: Use newer pipeline image from prow for the moment
  env/prow/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#138 fix: enable lighthouse PRs again
  env/templates/version-stream-update-cj.yaml
Labels: approved, lgtm, size/XS

#139 fix: Turn on metapipeline again
  env/prow/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#140 fix: Turn metapipeline back off
  env/prow/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#143 feat: add arcalos secrets
  env/templates/arcalos-secret.yaml
  env/values.tmpl.yaml
Labels: approved, size/M

#144 fix: switch bdd cleanup script to use jenkins-x-bdd3 project
  env/templates/e2e-gc-cj.yaml
Labels: approved, lgtm, size/XS

#146 fix: Switch a few images to use version stream instead of explicit
  env/jenkins-x-platform/values.tmpl.yaml
  env/prow/values.tmpl.yaml
  env/templates/copy-charts-index-cj.yaml
  env/templates/e2e-gc-cj.yaml
  env/templates/version-stream-update-cj.yaml
Labels: approved, lgtm, size/S

#152 fix: arcalos pipeline as we need pipeline email now too
  env/templates/arcalos-secret.yaml
  env/values.tmpl.yaml
Labels: approved, size/XS

#156 chore: added in source repo for jx-app-kuberhealthy
  repositories/templates/jenkins-x-apps.yaml
Labels: approved, lgtm, size/S

#160 chore: added in source repo for arcalos
  repositories/templates/cloudbees.yaml
Labels: approved, size/S

#164 feat: adding jenkins-x-github-app
  repositories/templates/cloudbees.yaml
Labels: approved, lgtm, size/S

#165 feat: add replace:true to presubmits to avoid having the default scheduler context for ci builds
  env/templates/ci-scheduler.yaml
Labels: approved, lgtm, size/XS

#169 chore: Add boot-vault context to jx
  env/templates/jx-scheduler.yaml
Labels: approved, lgtm, size/S

#170 fix: Use consistent source repo name for jenkins-x-github-app
  repositories/templates/cloudbees.yaml
Labels: approved, lgtm, size/XS

#171 chore: add in config & cron for cloudbees/arcalos-jenkins-x-versions
  env/templates/arcalos-version-stream-update-cj.yaml
  env/templates/arcalos-versions-scheduler.yaml
  repositories/templates/arcalos-versions-group.yaml
  repositories/templates/cloudbees.yaml
Labels: approved, lgtm, size/L

#167 fix: Clean up jenkins-x-versions contexts
  env/templates/jx-versions-scheduler.yaml
Labels: approved, lgtm, size/S

#173 chore: Make boot-vault context required on jx PRs
  env/templates/jx-scheduler.yaml
Labels: approved, lgtm, size/XS

#178 fix: Switch to metapipeline again
  env/prow/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#180 fix: Use temporary image for controllerbuild
  env/jenkins-x-platform/values.tmpl.yaml
Labels: approved, size/XS
