Repository jenkins-x/environment-tekton-weasel-dev, pull requests merged in 2019-11, with the labels that each got.

#217 chore: add CB chartmuseum secret
  env/templates/cb-chartmuseum-secret.yaml
  env/values.tmpl.yaml
Labels: approved, size/S

#219 fix: add bucketrepo bdd test
  env/templates/jx-versions-scheduler.yaml
Labels: size/M

#221 fix: remove bucketrepo from the required bdd tests
  env/templates/jx-versions-scheduler.yaml
Labels: approved, lgtm, size/XS

#230 chore: add jx-segment-controller
  repositories/templates/cloudbees.yaml
Labels: approved, lgtm, size/S

#233 feat: import the jx-release-version project
  repositories/templates/jenkins-x.yaml
Labels: approved, lgtm, size/S

#235 chore: remove execute permissions on some files
  systems/cm/Chart.yaml
  systems/cm/requirements.yaml
  systems/cm/values.yaml
  systems/jxing/Chart.yaml
  systems/jxing/requirements.yaml
  systems/jxing/values.yaml
  systems/vault/Chart.yaml
  systems/vault/values.yaml
Labels: size/XS

#236 fix: Bump arcalos version update cronjob builder image
  env/templates/arcalos-version-stream-update-cj.yaml
Labels: approved, lgtm, size/XS

#237 fix: image format typo
  env/templates/arcalos-version-stream-update-cj.yaml
Labels: approved, lgtm, size/XS

#239 chore: add jx-arcalos-role-controller
  repositories/templates/cloudbees.yaml
Labels: approved, lgtm, size/S

#242 fix: lets use a jx helm function to use the version stream version
  env/templates/arcalos-cleanup-cj.yaml
  env/templates/arcalos-version-stream-update-cj.yaml
  env/templates/copy-charts-index-cj.yaml
  env/templates/e2e-gc-cj.yaml
  env/templates/version-stream-update-cj.yaml
  env/values.tmpl.yaml
Labels: approved, size/S

#250 chore: Disable prow-build since we don't need it
  env/prow/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#260 chore: add segment write key for arcalos PRs
  env/templates/arcalos-secret.yaml
  env/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#265 fix: use a newer builder for dex
  env/jx-app-sso/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#273 chore: Run bdd-jx postsubmits from `jenkins-x-release.yml`.
  env/templates/bdd-jx-scheduler.yaml
  repositories/templates/bdd-jx-group.yaml
  repositories/templates/jenkins-x.yaml
Labels: approved, lgtm, size/M

#275 chore: Add new Lighthouse contexts for BDD tests
  env/templates/lh-scheduler.yaml
  repositories/templates/lh-group.yaml
Labels: approved, size/L

#280 fix: Remove cloudbees-jenkins-x-distro repo
  repositories/templates/cloudbees.yaml
Labels: approved, lgtm, size/S

#281 chore: Make github and ghe contexts for lighthouse required
  env/templates/lh-scheduler.yaml
Labels: approved, size/XS

#282 chore: Set a higher memory limit for jxui than the default
  OWNERS
  env/jx-app-ui/values.tmpl.yaml
Labels: approved, size/XS

#284 fix: jxui, not jx-app-ui
  env/jxui/values.tmpl.yaml
Labels: approved, size/XS

#285 fix: Allow updatebot for dev env, one more try at overriding ui limits
  env/templates/dev-env-scheduler.yaml
  env/templates/dev-repo.yaml
  env/ui/values.tmpl.yaml
Labels: approved, size/L

#287 feat: adding repo for terraform-google-jx
  repositories/templates/jenkins-x.yaml
Labels: approved, lgtm, size/S

#288 chore: add macox to owners
  OWNERS
Labels: approved, lgtm, size/XS

#290 fix: Stop doing git credentials stuff in build controller
  env/jenkins-x-platform/values.tmpl.yaml
Labels: approved, size/XS

#293 chore: enable debug and make cron schedule more frequent
  env/templates/arcalos-version-stream-update-cj.yaml
Labels: approved, lgtm, size/XS

#295 fix: excluding jx-repository-controller for arcalos updates
  env/templates/arcalos-version-stream-update-cj.yaml
Labels: approved, lgtm, size/XS

#296 chore: Turning on debug logging in build controller
  env/jenkins-x-platform/values.tmpl.yaml
Labels: approved, size/S

#297 fix: Fixing env specification for build controller
  env/jenkins-x-platform/values.tmpl.yaml
Labels: approved, size/S
