Repository jenkins-x/environment-tekton-weasel-dev, pull requests merged in 2019-12, with the labels that each got.

#301 fix: adding a unit context to scheduler configuration
  env/templates/jx-scheduler.yaml
Labels: approved, size/S

#303 chore: Add versions and LH bot test users
  env/templates/lighthouse-test-secret.yaml
  env/templates/versions-test-secret.yaml
  env/values.tmpl.yaml
Labels: approved, lgtm, size/M

#304 chore: re-enable the boot-vault bdd test on boot config repository
  env/templates/boot-config-scheduler.yaml
Labels: approved, lgtm, size/S

#307 chore: add plantuml
  env/plantuml/values.tmpl.yaml
  env/requirements.yaml
Labels: approved, lgtm, size/XS

#308 chore: use clusterip for service
  env/plantuml/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#310 chore: Add boot upgrade bdd context
  OWNERS
  env/templates/jx-versions-scheduler.yaml
Labels: approved, lgtm, size/M

#311 chore: add arch-docs
  repositories/templates/cloudbees.yaml
Labels: approved, lgtm, size/S

#306 fix: quote boolean label value in namespace template
  env/templates/000-namespace.yaml
Labels: approved, lgtm, size/XS

#312 feat: add repo for hugo-extended-docker
  repositories/templates/jenkins-x.yaml
Labels: approved, lgtm, size/S

#314 fix: Proper naming of hugo-extended-docker
  repositories/templates/jenkins-x.yaml
Labels: approved, size/XS
