Repository jenkins-x/environment-tekton-weasel-dev, pull requests merged in 2020-05, with the labels that each got.

#570 chore: updated cleanup job to use new secret name
  env/templates/arcalos-cleanup-cj.yaml
Labels: approved, lgtm, size/XS

#551 chore: Remove obsolete plugins from scheduler config
  env/templates/default-scheduler.yaml
  env/templates/dev-env-scheduler.yaml
  env/templates/env-scheduler.yaml
  env/templates/whitesource-scheduler.yaml
Labels: approved, lgtm, size/S

#555 fix: Somehow Prow came back. Let's not let that happen again.
  env/prow/values.tmpl.yaml
  env/requirements.yaml
Labels: approved, lgtm, size/S

#575 chore: Get rid of boot-lh versions context
  env/templates/jx-versions-scheduler.yaml
Labels: approved, lgtm, size/XS

#576 chore: add repo configuration for the saas-cli
  repositories/templates/cloudbees.yaml
Labels: size/S

#578 chore: added dog images repo
  repositories/templates/jenkins-x-images.yaml
Labels: approved, lgtm, size/S

#581 chore: adding codegen context
  env/templates/jx-scheduler.yaml
Labels: approved, lgtm, size/S

#582 chore: making codegen a required context
  env/templates/jx-scheduler.yaml
Labels: approved, lgtm, size/XS

#583 chore: Add BBS approver user secret
  env/templates/git-test-bbs-approver-secret.yaml
  env/values.tmpl.yaml
Labels: approved, size/S

#584 fix: Add legacy hmac-token secret
  env/templates/hmacsecret.yaml
  env/values.tmpl.yaml
Labels: approved, size/XS

#585 chore: remove old envs and add new play env
  env/templates/arcalos-play-mgmt-env.yaml
  env/templates/raccoon-env.yaml
Labels: approved, lgtm, size/S

#590 chore: Add sonar app
  repositories/templates/jenkins-x-apps.yaml
Labels: size/S

#589 chore: Temporarily pinning e2e gc job to older jx image
  env/templates/e2e-gc-cj.yaml
Labels: approved, size/XS

#592 chore: Make BitBucket Server context required for Lighthouse PRs
  env/templates/lh-scheduler.yaml
Labels: approved, size/XS

#598 fix: Turn off gh-pages reporting in build controller
  env/jenkins-x-platform/values.tmpl.yaml
Labels: approved, size/XS

#599 chore: use the sac image for running the cleanup script
  env/templates/arcalos-cleanup-cj.yaml
Labels: approved, size/XS

#602 chore: Add cronjob syncing quay.io nginx ingress images to gcr.io
  env/templates/sync-nginx-images-cj.yaml
  env/templates/sync-nginx-images-script-cm.yaml
Labels: approved, lgtm, size/M
