Repository jenkins-x/environment-tekton-weasel-dev, pull requests merged in 2020-06, with the labels that each got.

#611 chore: Add new lighthouse-config library repository
  repositories/templates/jenkins-x.yaml
Labels: approved, lgtm, size/S

#613 fix: Revert to UI 0.0.1270 for the moment
  env/requirements.yaml
Labels: approved, lgtm, size/XS

#614 chore: try an earlier UI version
  env/requirements.yaml
Labels: approved, size/XS

#615 fix: set sso create to true
  env/requirements.yaml
  env/ui/values.tmpl.yaml
Labels: approved, lgtm, size/S

#616 fix: jxui sso config
  env/ui/values.tmpl.yaml
Labels: approved, lgtm, size/S

#617 fix: rollback sso fix attempts
  env/requirements.yaml
  env/ui/values.tmpl.yaml
Labels: approved, lgtm, size/S

#618 fix: jxui sso config
  env/requirements.yaml
  env/ui/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#619 fix: Use v1.0.489 tag in version stream
  jx-requirements.yml
Labels: approved, lgtm, size/XS

#620 fix: Use the sha for the correct version stream tag, not the wrong one I did initially
  jx-requirements.yml
Labels: approved, size/XS

#621 chore: arcalos beta preview sa
  env/templates/arcalos-beta-preview-secret.yaml
  env/values.tmpl.yaml
Labels: approved, size/S

#622 chore: import jx-api & jx-kube-client
  repositories/templates/jenkins-x.yaml
Labels: approved, lgtm, size/M

#623 chore: Import the kubeless app
  repositories/templates/jenkins-x-apps.yaml
Labels: approved, lgtm, size/S

#624 chore: import jx-vault-client
  repositories/templates/jenkins-x.yaml
Labels: approved, lgtm, size/S

#625 chore: update path of beta preview secret value
  env/templates/arcalos-beta-preview-secret.yaml
Labels: approved, lgtm, size/XS

#626 chore: add jx-role-controller repo
  repositories/templates/jenkins-x.yaml
Labels: approved, lgtm, size/S

#627 chore: Disable cronjobs moving to oss-weasel
  env/templates/arcalos-cleanup-cj.yaml
  env/templates/arcalos-version-stream-update-cj.yaml
  env/templates/e2e-gc-cj.yaml
  env/templates/jx-issue-lifecycle-close-cj.yaml
  env/templates/jx-issue-lifecycle-rotten-cj.yaml
  env/templates/jx-issue-lifecycle-stale-cj.yaml
  env/templates/sync-nginx-images-cj.yaml
  env/templates/version-stream-update-cj.yaml
Labels: approved, lgtm, size/S

#628 chore: Move jenkins-x/lighthouse repository to oss-weasel
  repositories/templates/lh-group.yaml
Labels: approved, size/XS

#629 chore: Actually remove Lighthouse
  repositories/templates/jenkins-x.yaml
  repositories/templates/lh-group.yaml
Labels: approved, size/S

#630 chore: Disable the copy-chart-index cronjob
  env/templates/copy-charts-index-cj.yaml
Labels: approved, size/XS

#631 chore: Remove SourceRepositories for move to oss-weasel
  repositories/templates/arcalos-boot-config-group.yaml
  repositories/templates/arcalos-versions-group.yaml
  repositories/templates/bdd-jx-group.yaml
  repositories/templates/boot-config-group.yaml
  repositories/templates/ci-group.yaml
  repositories/templates/cloudbees.yaml
  repositories/templates/default-group.yaml
  repositories/templates/jenkins-x-apps.yaml
  repositories/templates/jenkins-x-charts.yaml
  repositories/templates/jenkins-x-images.yaml
  repositories/templates/jenkins-x.yaml
  repositories/templates/jx-group.yaml
  repositories/templates/jx-versions-group.yaml
  repositories/templates/lh-group.yaml
  repositories/templates/rebase-and-lgtm-group.yaml
  repositories/templates/whitesource-group.yaml
Labels: approved, lgtm, size/XXL

#633 fix: whoops needed default-group.yaml
  repositories/templates/default-group.yaml
Labels: approved, size/S

#632 chore: Update jx-requirements.yml
  env/templates/cert-manager-prod-certificate.yaml
  env/templates/cert-manager-prod-issuer.yaml
  env/templates/cert-manager-staging-certificate.yaml
  env/templates/cert-manager-staging-issuer.yaml
  jx-requirements.yml
Labels: approved, size/M
