Repository jenkins-x/environment-tekton-weasel-dev, pull requests merged in 2020-02, with the labels that each got.

#360 fix: add new chart
  repositories/templates/jenkins-x-charts.yaml
Labels: approved, size/S

#362 fix: add knative-serving chart
  repositories/templates/jenkins-x-charts.yaml
Labels: approved, size/S

#363 chore: add jx-sdm-app
  env/jx-sdm-app/values.tmpl.yaml
  env/requirements.yaml
  env/tekton-sdm-app/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#364 fix: Remove jxui-frontend contexts.
  repositories/templates/ci-group.yaml
  repositories/templates/cloudbees-ci.yaml
Labels: approved, size/S

#365 chore: update to new jx-sdm-app to avoid oom
  env/requirements.yaml
Labels: approved, lgtm, size/XS

#366 chore: upgrade jx-sdm-app to 0.0.7
  env/requirements.yaml
Labels: approved, size/XS

#371 chore: move to jx-sdm-app 0.0.8
  env/requirements.yaml
Labels: approved, lgtm, size/XS

#372 chore(deps): bump jx-sdm-app to 0.0.9
  env/jx-sdm-app/values.tmpl.yaml
  env/requirements.yaml
Labels: approved, lgtm, size/XS

#374 chore: Add jx-app-fossa repo
  repositories/templates/jenkins-x-apps.yaml
Labels: approved, lgtm, size/S

#375 feat: add arcalos configuration configmap
  env/templates/arcalos-config-configmap.yaml
Labels: approved, lgtm, size/XS

#377 chore: add rollout-sdm-app
  repositories/templates/cloudbees.yaml
Labels: approved, lgtm, size/S

#380 chore: adds source repo arcalos-config
  repositories/templates/cloudbees.yaml
Labels: approved, lgtm, size/S

#378 chore: Keep PR builds for at least 5 days.
  OWNERS
  env/jenkins-x-platform/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#382 chore: re-able auto update of nginx-ingress controller
  env/templates/arcalos-version-stream-update-cj.yaml
Labels: approved, lgtm, size/XS

#379 fix: Re-enable automatic updating of nginx-ingress chart for version stream
  env/templates/version-stream-update-cj.yaml
Labels: approved, lgtm, size/XS

#381 chore: Switch to Lighthouse rather than Prow
  jx-requirements.yml
Labels: approved, lgtm, size/XS

#383 chore: add cloud-build-sdm-app
  repositories/templates/cloudbees.yaml
Labels: approved, lgtm, size/S

#384 chore: Revert to Prow due to PRs not getting log links
  env/jenkins-x-platform/values.tmpl.yaml
  jx-requirements.yml
Labels: approved, size/XS

#385 fix: BitBucket does not actually work well enough to be a blocker for LH
  env/templates/lh-scheduler.yaml
Labels: approved, size/XS

#386 fix: add a new bdd test context to version stream
  env/templates/jx-versions-scheduler.yaml
Labels: approved, lgtm, size/M

#390 fix: boot-alpha shouldn’t be required yet
  env/templates/jx-versions-scheduler.yaml
Labels: approved, size/XS

#391 chore: Use gsutil and set cache control when copying charts
  env/templates/copy-charts-index-cj.yaml
Labels: approved, lgtm, size/S

#392 chore: Turn off caching completely for chartmuseum index.yaml
  env/templates/copy-charts-index-cj.yaml
Labels: approved, size/XS

#389 chore: Switch to Lighthouse post-log link and retest fixes
  env/jenkins-x-platform/values.tmpl.yaml
  jx-requirements.yml
Labels: approved, lgtm, size/XS

#393 chore: Revert back to Prow again
  jx-requirements.yml
Labels: approved, size/XS

#394 chore: Fix my mixup in requirements.yaml, turn on Lighthouse again
  env/requirements.yaml
  jx-requirements.yml
Labels: approved, lgtm, size/XS

#395 chore: Bump Lighthouse replicaCount
  env/lighthouse/values.tmpl.yaml
Labels: approved, size/XS

#396 chore: Revert to Prow
  jx-requirements.yml
Labels: approved, size/XS

#397 chore: Switch to LH after latest fixes
  jx-requirements.yml
Labels: approved, size/XS

#398 chore: Revert to Prow from LH dogfooding
  jx-requirements.yml
Labels: approved, size/XS

#387 chore: switch arcalos to use alpha environment
  env/templates/arcalos-config-configmap.yaml
Labels: approved, lgtm, size/XS

#399 chore: Dogfood Lighthouse again, Feb 28
  env/requirements.yaml
  jx-requirements.yml
Labels: approved, size/XS

#400 chore: Revert to Prow, Feb 28
  env/requirements.yaml
  jx-requirements.yml
Labels: approved, size/XS
