Repository jenkins-x/environment-tekton-weasel-dev, pull requests merged in 2020-03, with the labels that each got.

#359 fix: remove hook certmanager annotations as they alter the cert-manag…
  env/templates/700-hook-ing.yaml
Labels: approved, lgtm, size/XS

#406 fix: add more repos
  repositories/templates/jenkins-x.yaml
Labels: approved, size/M

#407 chore: added hornberyl env as manual promotion option
  env/templates/hornberyl-env.yaml
Labels: approved, lgtm, size/S

#408 fix: add a helm3 multi cluster bdd test
  env/templates/jx-versions-scheduler.yaml
Labels: approved, size/M

#405 feat: add a whitesource postsubmit job to jx repository
  env/templates/jx-scheduler.yaml
  env/templates/whitesource-secret.yaml
  env/values.tmpl.yaml
Labels: approved, lgtm, size/M

#409 chore: added arcalos-prod-mgmt environment to deploy to
  env/templates/arcalos-prod-mgmt.yaml
Labels: approved, lgtm, size/S

#411 feat: enable the whitesource postsubmit job for lighthouse, bucketrepo, sso-operator
  env/templates/lh-scheduler.yaml
  env/templates/whitesource-scheduler.yaml
  repositories/templates/whitesource-group.yaml
Labels: approved, lgtm, size/L

#412 feat: add more repositories to whitesource source repository group
  repositories/templates/whitesource-group.yaml
Labels: approved, lgtm, size/S

#417 chore: add arcalos-setup repository
  repositories/templates/cloudbees.yaml
Labels: approved, lgtm, size/S

#420 feat: added the arcalos-alpha-prod-secret
  env/templates/arcalos-alpha-prod-secret.yaml
Labels: approved, lgtm, size/S

#422 fix: typo in secret name
  env/templates/arcalos-alpha-prod-secret.yaml
Labels: approved, lgtm, size/XS

#424 chore: set new environment name value in configmap
  env/templates/arcalos-config-configmap.yaml
Labels: approved, lgtm, size/XS

#427 feat: added lint context to whitesource scheduler
  env/templates/whitesource-scheduler.yaml
Labels: approved, lgtm, size/S

#418 fix: enable the helm 3 single + multi cluster BDD tests
  env/templates/arcalos-version-stream-update-cj.yaml
  env/templates/jx-versions-scheduler.yaml
  env/templates/version-stream-update-cj.yaml
Labels: size/XS

#433 fix: re-enable jx-repository-controller in version stream pr
  env/templates/arcalos-version-stream-update-cj.yaml
Labels: approved, lgtm, size/XS

#431 chore: remove unrequired values from arcalos-alpha-prod-secret
  env/templates/arcalos-alpha-prod-secret.yaml
Labels: approved, lgtm, size/XS

#432 chore: remove unrequired values from arcalos-prod-secret
  env/templates/arcalos-prod-secret.yaml
Labels: approved, lgtm, size/XS

#430 chore: remove unrequired values from arcalos-secret
  env/templates/arcalos-secret.yaml
Labels: approved, lgtm, size/XS

#434 fix: Revert - re-enable jx-repository-controller in version stream pr
  env/templates/arcalos-version-stream-update-cj.yaml
Labels: approved, lgtm, size/XS

#437 feat: add the eks terraform repo to the cluster
  repositories/templates/jenkins-x.yaml
Labels: approved, lgtm, size/S

#441 chore: Add GHE secret for an approver user
  env/templates/git-test-ghe-approver-secret.yaml
  env/values.tmpl.yaml
Labels: approved, size/S

#445 fix: Don't run the helm3 and helm3-mc version stream tests automatically
  env/templates/jx-versions-scheduler.yaml
Labels: approved, lgtm, size/XS

#447 chore: Resurrect the lifecycle jobs
  env/templates/jx-issue-lifecycle-close-cj.yaml
  env/templates/jx-issue-lifecycle-rotten-cj.yaml
  env/templates/jx-issue-lifecycle-stale-cj.yaml
Labels: approved, size/L

#448 feat: create aws creds secret and add them to the values file
  env/templates/aws-creds-secret.yaml
  env/values.tmpl.yaml
Labels: approved, lgtm, size/S

#451 chore: Add rebase-and-lgtm-scheduler
  env/templates/rebase-and-lgtm-scheduler.yaml
  repositories/templates/rebase-and-lgtm-group.yaml
Labels: approved, lgtm, size/M

#435 fix: another attempt to include jx-repository-controller
  env/templates/arcalos-version-stream-update-cj.yaml
Labels: approved, lgtm, size/XS

#452 revert: "fix: another attempt to include jx-repository-controller"
  env/templates/arcalos-version-stream-update-cj.yaml
Labels: approved, lgtm, size/XS

#453 fix: add acme chart
  repositories/templates/jenkins-x-charts.yaml
Labels: approved, size/S

#454 fix: add istio chart
  repositories/templates/jenkins-x-charts.yaml
Labels: approved, size/S

#456 chore(deps): bump cloudbees/jx-sdm-app from v0.0.9 to v0.0.17
  env/requirements.yaml
Labels: approved, lgtm, size/XS

#457 chore: let jx-docs repo use the rebase and lgtm scheduler
  repositories/templates/rebase-and-lgtm-group.yaml
Labels: approved, lgtm, size/XS

#459 chore: add jx-logging SourceRepository
  repositories/templates/jenkins-x.yaml
Labels: approved, lgtm, size/S

#466 chore: let terraform-aws-eks-jx repo use the rebase and lgtm scheduler
  repositories/templates/rebase-and-lgtm-group.yaml
Labels: approved, lgtm, size/XS

#477 fix: try and include the jx-repository-controller again
  env/templates/arcalos-version-stream-update-cj.yaml
Labels: approved, lgtm, size/XS

#484 fix: corrected repository name for jenkins-x-terraform-aws-eks-jx in …
  repositories/templates/rebase-and-lgtm-group.yaml
Labels: approved, lgtm, size/XS

#486 fix: Pin nginx-ingress chart to 1.34.2.
  env/templates/arcalos-version-stream-update-cj.yaml
  env/templates/version-stream-update-cj.yaml
Labels: approved, lgtm, size/XS

#488 chore: adding jenkins-x-terraform-azurerm-jx to rebase-and-lgtm-sched…
  repositories/templates/rebase-and-lgtm-group.yaml
Labels: approved, lgtm, size/XS
