Repository jenkins-x/environment-tekton-weasel-dev, pull requests merged in 2020-01, with the labels that each got.

#316 fix: Rename Lighthouse's Bitbucket Server context to bbs
  env/templates/lh-scheduler.yaml
Labels: approved, size/XS

#317 fix: Make gitlab context for Lighthouse required
  env/templates/lh-scheduler.yaml
Labels: approved, size/XS

#318 chore: Enable upgrade test
  env/templates/jx-versions-scheduler.yaml
Labels: approved, lgtm, size/XS

#321 chore: enable CI/CD for jx-app-replicator
  repositories/templates/jenkins-x-apps.yaml
Labels: approved, size/S

#322 chore: Add optional boot-lh-ghe context to jx.
  env/templates/jx-scheduler.yaml
Labels: approved, lgtm, size/S

#323 fix: Whoops, boot-lh-ghe should not always run on jx
  env/templates/jx-scheduler.yaml
Labels: approved, size/XS

#324 chore: Require BitBucket context on Lighthouse
  env/templates/lh-scheduler.yaml
Labels: approved, lgtm, size/XS

#325 chore: Add jx-convert-jenkinsfile repo
  repositories/templates/jenkins-x.yaml
Labels: approved, lgtm, size/S

#326 chore: add velero-backup pipeline config
  repositories/templates/jenkins-x-charts.yaml
Labels: approved, size/S

#327 chore: Stop updating stable/nginx-ingress in version stream update cronjob
  env/templates/version-stream-update-cj.yaml
Labels: approved, size/XS

#329 fix: exclude stable/nginx-ingress from arcalos update
  env/templates/arcalos-version-stream-update-cj.yaml
Labels: approved, lgtm, size/XS

#332 fix: Make jenkins-x-boot-config use rebase for PR merges
  env/templates/boot-config-scheduler.yaml
Labels: approved, lgtm, size/XS

#334 chore: Disable BBS context on Lighthouse due to BBS test instance issues
  env/templates/lh-scheduler.yaml
Labels: approved, size/XS

#335 chore: add tekton-sdm-app
  repositories/templates/cloudbees.yaml
Labels: approved, lgtm, size/S

#337 fix: add 2 new repos
  repositories/templates/jenkins-x-charts.yaml
  repositories/templates/jenkins-x.yaml
Labels: approved, lgtm, size/M

#338 chore: add jenkins-x-images/git
  repositories/templates/jenkins-x-images.yaml
Labels: approved, lgtm, size/S

#340 chore: Convenience /test commands for Lighthouse repo
  env/templates/lh-scheduler.yaml
Labels: approved, size/XS

#341 chore: Turn BitBucket Server back on for Lighthouse tests
  env/templates/lh-scheduler.yaml
Labels: approved, size/XS

#342 chore: added arcalos-prod-secret
  env/templates/arcalos-prod-secret.yaml
  env/values.tmpl.yaml
Labels: approved, lgtm, size/S

#344 fix: Rename tekton-sdm-app SR to match standard format
  repositories/templates/cloudbees.yaml
Labels: approved, lgtm, size/XS

#343 chore: removed exclusion on jx-repository-controller
  env/templates/arcalos-version-stream-update-cj.yaml
Labels: approved, lgtm, size/XS

#345 chore: adding terraform-secret
  env/templates/terraform-secret.yaml
  env/values.tmpl.yaml
Labels: approved, lgtm, size/S

#347 chore: making unit context always run
  env/templates/jx-scheduler.yaml
Labels: approved, size/XS

#349 chore: adds source repo arcalos-instance-template
  repositories/templates/cloudbees.yaml
Labels: approved, lgtm, size/S

#348 chore: Add new migrate-from-prow optional context to Lighthouse
  env/templates/lh-scheduler.yaml
Labels: approved, size/M

#350 chore: add SDM connector
  env/requirements.yaml
  env/tekton-sdm-app/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#351 chore: Update lighthouse values.tmpl.yaml from upstream
  env/lighthouse/values.tmpl.yaml
  jenkins-x.yml
Labels: approved, lgtm, size/S

#352 fix: Update the release pipeline too
  jenkins-x.yml
Labels: approved, lgtm, size/XS

#353 chore: Update lighthouse values that'll work with ancient builder
  env/lighthouse/values.tmpl.yaml
  env/requirements.yaml
Labels: approved, lgtm, size/S

#354 chore: add jx-sdm-app
  repositories/templates/cloudbees.yaml
Labels: approved, lgtm, size/S

#356 chore: revert - removed exclusion on jx-repository-controller
  env/templates/arcalos-version-stream-update-cj.yaml
Labels: approved, lgtm, size/XS

#357 fix: correct arcalos-instance-template config
  repositories/templates/cloudbees.yaml
Labels: approved, lgtm, size/XS
