Repository jenkins-x/environment-tekton-weasel-dev, pull requests merged in 2020-04, with the labels that each got.

#508 chore: adding a tf-boot context to the jx repo
  env/templates/jx-scheduler.yaml
Labels: approved, lgtm, size/S

#509 chore: Bump to jx-app-athens 0.0.18 for Go 1.13 support
  env/jx-app-athens/templates/app.yaml
  env/requirements.yaml
Labels: approved, size/XS

#510 chore: Rollback to jx-app-athens 0.0.17
  env/jx-app-athens/templates/app.yaml
  env/requirements.yaml
Labels: approved, size/XS

#516 chore: added logrus-stackdriver-formatter repo
  repositories/templates/jenkins-x.yaml
Labels: approved, lgtm, size/S

#520 chore: Turn off static master BDD tests by default
  env/templates/jx-scheduler.yaml
  env/templates/jx-versions-scheduler.yaml
Labels: approved, lgtm, size/L

#528 chore: Upgrade Athens again
  env/jx-app-athens/templates/app.yaml
  env/requirements.yaml
Labels: approved, lgtm, size/XS

#530 fix: Lifecycle cronjobs don't query right with newlines in them
  env/templates/jx-issue-lifecycle-close-cj.yaml
  env/templates/jx-issue-lifecycle-rotten-cj.yaml
  env/templates/jx-issue-lifecycle-stale-cj.yaml
Labels: approved, lgtm, size/S

#541 feat: added datadog_dogrc_secret_template
  env/templates/datadog-dogrc-secret.yaml
  env/values.tmpl.yaml
Labels: approved, lgtm, size/S

#533 chore: Switch to Lighthouse yet again
  env/lighthouse/values.tmpl.yaml
  env/templates/jx-scheduler.yaml
  env/templates/jx-versions-scheduler.yaml
  jx-requirements.yml
Labels: approved, size/S

#543 fix: Don't pin lighthouse version
  env/requirements.yaml
Labels: approved, size/XS

#545 chore: Remove archived repos
  repositories/templates/jenkins-x.yaml
Labels: approved, size/M

#548 chore: Use a hardcoded Lighthouse version briefly
  env/requirements.yaml
Labels: approved, size/XS

#549 chore: Update to Lighthouse 0.0.546
  env/requirements.yaml
Labels: approved, size/XS

#550 chore: Switch back to version stream version of Lighthouse
  env/requirements.yaml
Labels: approved, size/XS

#552 fix: Lifecycle cronjobs were using old Prow secret
  env/templates/jx-issue-lifecycle-close-cj.yaml
  env/templates/jx-issue-lifecycle-rotten-cj.yaml
  env/templates/jx-issue-lifecycle-stale-cj.yaml
Labels: approved, size/XS

#561 chore: Add GitLab approver user secret
  env/templates/git-test-gitlab-approver-secret.yaml
  env/values.tmpl.yaml
Labels: approved, size/S

#566 chore: added arcalos-staging-mgmt environment
  env/templates/arcalos-staging-mgmt-env.yaml
Labels: approved, lgtm, size/S

#568 chore: remove arcalos-secret template
  env/templates/arcalos-prod-secret.yaml
  env/templates/arcalos-secret.yaml
Labels: approved, lgtm, size/M
